<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/underscore.min4511.js?ver=1.8.3'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/contact-form-7/includes/js/scriptsce52.js?ver=5.0.2'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/imagesloaded.min55a0.js?ver=3.2.0'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/masonry.mind617.js?ver=3.3.2'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/jquery/jquery.masonry.minef70.js?ver=3.1.2b'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/jquery/ui/core.mine899.js?ver=1.11.4'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/jquery/ui/widget.mine899.js?ver=1.11.4'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/jquery/ui/tabs.mine899.js?ver=1.11.4'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/timetable/js/jquery.ba-bbq.min1845.js?ver=4.9.6'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/timetable/js/jquery.carouFredSel-6.2.1-packed1845.js?ver=4.9.6'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/timetable/js/timetable1845.js?ver=4.9.6'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min44fd.js?ver=2.70'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min6b25.js?ver=2.1.4'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min6b00.js?ver=3.4.0'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min6b00.js?ver=3.4.0'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/bootstrap.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/mobilee0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/navigatione0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/jquery.prettyPhotoe0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/jquery.parallaxe0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/jquery.waypoints.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/inview.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/generale0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/skip-link-focus-fixe0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/retina.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/comment-reply.min1845.js?ver=4.9.6'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/owl.carousel.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-content/themes/kiddie/js/countUp.mine0ad.js?ver=3.401'); ?>'></script>
<script type='text/javascript' src='<?php echo base_url('assets/frontend/wp-includes/js/wp-embed.min1845.js?ver=4.9.6'); ?>'></script>