<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Agenda_model extends CI_Model
{
  public $table = 'agenda';
  public $id    = 'id_agenda';
  public $order = 'DESC';

  function get_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->result();    
  }
  
  function get_DataHalaman($perhalaman, $awal)
  {
    return $this->db->query('SELECT * FROM agenda ORDERS LIMIT '.$perhalaman.' OFFSET '.$awal.'')->result();
  }
  
  function get_pencarian_row($clue)
  {
    return $this->db->query('select * from agenda where judul like "%'.$clue.'%" or isi_agenda like "%'.$clue.'%" or uploader like "%'.$clue.'%" or time_upload like "%'.$clue.'%"')->num_rows();
  }
  
  function get_pencarian($clue, $perhalaman, $awal)
  {
    return $this->db->query('select * from agenda where judul like "%'.$clue.'%" or isi_agenda like "%'.$clue.'%" or uploader like "%'.$clue.'%" or time_upload like "%'.$clue.'%" order by time_upload limit '.$perhalaman.' offset '.$awal.'')->result();
  }
  
  function get_DataLimit()
  {
    return $this->db->query('SELECT * FROM agenda LIMIT 3')->result();
  }
  
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_all_random()
  {
    $this->db->limit(4); 
    $this->db->order_by($this->id, 'random');
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    $this->db->or_where('judul_seo', $id);
    return $this->db->get($this->table)->row();    
  }

  function get_all_arsip($per_page,$dari)
  {
    $query = $this->db->get($this->table,$per_page,$dari);
    return $query->result();
  }
  
  // get total rows
  function total_rows() {
    return $this->db->get($this->table)->num_rows();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

}

/* End of file Berita_model.php */
/* Location: ./application/models/Berita_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */