<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Artikel_model extends CI_Model
{
  public $table = 'artikel';
  public $id    = 'id_artikel';
  public $order = 'DESC';

  function get_kategori_row($clue)
  {
    return $this->db->query('select * from artikel where kategori = "'.$clue.'"')->num_rows();
  }
  
  function get_kategori($clue, $perhalaman, $awal)
  {
    return $this->db->query('select * from artikel where kategori = "'.$clue.'" limit '.$perhalaman.' offset '.$awal.'')->result();
  }
  
  function get_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->result();    
  }
  
  function get_DataHalaman($perhalaman, $awal)
  {
    return $this->db->query('SELECT * FROM artikel ORDERS LIMIT '.$perhalaman.' OFFSET '.$awal.'')->result();
  }
  
  function get_pencarian_row($clue)
  {
    return $this->db->query('select * from artikel where judul_artikel like "%'.$clue.'%" or isi_artikel like "%'.$clue.'%" or kategori like "%'.$clue.'%" or uploader like "%'.$clue.'%" or time_upload like "%'.$clue.'%"')->num_rows();
  }
  
  function get_pencarian($clue, $perhalaman, $awal)
  {
    return $this->db->query('select * from artikel where judul_artikel like "%'.$clue.'%" or isi_artikel like "%'.$clue.'%" or kategori like "%'.$clue.'%" or uploader like "%'.$clue.'%" or time_upload like "%'.$clue.'%" order by time_upload limit '.$perhalaman.' offset '.$awal.'')->result();
  }
  
  function get_DataLimit()
  {
    return $this->db->query('SELECT * FROM artikel LIMIT 3')->result();
  }
  
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_all_random()
  {
    $this->db->limit(4); 
    $this->db->order_by($this->id, 'random');
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();    
  }

  function get_all_arsip($per_page,$dari)
  {
    $query = $this->db->get($this->table,$per_page,$dari);
    return $query->result();
  }
  
  // get total rows
  function total_rows() {
    return $this->db->get($this->table)->num_rows();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }
  
  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  // get all
  function get_cari_artikel()
  {
    $artikel = $this->input->post('artikel');

    $this->db->like('judul_artikel', $artikel);
    return $this->db->get($this->table)->result();
  }

}

/* End of file Berita_model.php */
/* Location: ./application/models/Berita_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */